### ISSUE TITLE
CI: Eagerly cancel unrelevant CI jobs. 

### ISSUE THREAD

**Issue by duesee** [openmls/openmls#1062]
We could use ...

```yaml
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

... to eagerly cancel workflows that are superseded by another workflow. If I get the [documentation](https://docs.github.com/en/actions/using-jobs/using-concurrency) right we could use this to cancel, e.g., outdated workflows when a new commit is made in a PR. I would propose to get that in place to decrease CI work (and time).

I marked this as a question for now. Maybe there is a reason we want to finish these jobs.
